# proto-file: third_party/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "93de65a7-8566-4106-96c2-91d3ea82545e"
plan_id:  "PF-1.24"
description:  "Add and remove interface bound to PBF"
testbed:  TESTBED_DUT_ATE_4LINKS
platform_exceptions:  {
  platform:  {
    vendor:  NOKIA
  }
  deviations:  {
    static_protocol_name:  "static"
    interface_enabled:  true
    interface_ref_interface_id_format: true

  }
}
platform_exceptions:  {
  platform:  {
    vendor:  ARISTA
  }
  deviations:  {
    static_protocol_name:  "STATIC"
    interface_enabled:  true
    default_network_instance:  "default"
    interface_config_vrf_before_address: true

  }
}
platform_exceptions:  {
  platform:  {
    vendor:  CISCO
  }
  deviations:  {
    interface_ref_interface_id_format: true
  }
}
